# Generated by Django 4.2.5 on 2023-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'db_table': 'stu_table',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Teacher',
                'db_table': 'tec_table',
            },
        ),
    ]
